- name: Get a cert from an https port
  community.crypto.get_certificate:
    host: "{{ server }}"
    port: 443
  delegate_to: localhost
  run_once: true
  register: cert
  
- name: How many days until cert expires
  ansible.builtin.debug:
    msg: "cert expires in: {{ expire_days }} days."
  vars:
    expire_days: "{{ (( cert.not_after | to_datetime('%Y%m%d%H%M%SZ')) - (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ')) ).days }}"
    
