- name: Send Notification to teams channel
  uri:
    url: "https://dell.webhook.office.com/bhookb2/5d8d447e-ee92-4d11-be05-70fe1b0172b3@3048dc87-43f0-4100-9acbae1971c79395/IncomingWebhook/e060b4d2de024bb5a68ffd49eee69a8e/b8066acea348-45f5-8461-a4b33df38719"
    method: POST
    body_format: json
    body:
      title: "Alert!!! the bellow certificates is about to expire:"
      text: "Server: {{ server }} will expire in {{ expire_days }} days"
  when: expire_days < 90
